### ISSUE TITLE
Changes before 32c3

### ISSUE THREAD

**Issue by Ghabry** [EasyRPG/easy-rpg.org#2]
Deadline: 27th December

- [x] Remove DSi and PSP logo, add Android, HTML5 and Pandora (?)
- [ ] Add a link to the browser games somewhere (at the start page and in download section?)
- [ ] Game browser to select between popular games:
- [x] Add a few assets (Chara1 and Vehicle) to fix Warnings for TestGame
- [x] Mention Player before Editor on startpage ????????????

Game list: (to be discussed)

TestGame, Yume Nikki, Ib, ... ?

**Comment by carstene1ns** [comment]
About 1: maybe adding some page/section in the /player/ namespace is worth with some history about supported platforms, then the logo could be a link to that.
In this section add some words why port X is not maintained/working anymore.

**Comment by carstene1ns** [comment]
![platforms](http://p.f4ke.de/66AbcZs44C.png)

**Comment by fdelapena** [comment]
Vehicle candidates:
http://opengameart.org/content/16x16-fantasy-pixel-art-vehicles

**Comment by Ghabry** [comment]
We could also use an empty vehicle file. Just to get rid of the warning... will break the vehicle test but everything else will work ^^

**Comment by fdelapena** [comment]
Faceset could be filled with front characters instead of black squares too.

**Comment by carstene1ns** [comment]
I just made a simple replacement graphics for now:
![vehicle](http://picload.org/image/pwcoilp/vehicle.png)

**Comment by carstene1ns** [comment]
btw. `Chara1` is already present in Testgame-2000.

**Comment by fdelapena** [comment]
![chara1](https://cloud.githubusercontent.com/assets/174885/11904362/3c2c6ffc-a585-11e5-8702-178090651bf5.png)
FaceSet/Chara1.png replacement

**Comment by Ghabry** [comment]
:+1:

**Comment by Ghabry** [comment]
Okay, perfect.
Because it's happening soon I think the only very important thing left are links to the in-browser game. Would be good to have this resolved in the next 48 hours.

**Comment by carstene1ns** [comment]
Sorry, had no time to finish the game showcase or upload new games yet, so let's just stay safe and only provide the testgame for now.
