### ISSUE TITLE
Restructure Player download page

### ISSUE THREAD

**Issue by carstene1ns** [EasyRPG/easy-rpg.org#3]
The current download page is a mess.

Ideally, it should have some big button to download Player for the current platform and a clean table under it for other platforms.
As the platform is reported by the browser, this could be done using an unobtrusive javascript, that should fallback gracefully (i.e. no big button).
It could also be done on server side using php, etc., however this might have quite an impact on performance.

Given the limited time until #2, only the restructuring could take place now, the platform choosing might come later.

**Comment by carstene1ns** [comment]
Experimenting with tables:
![table](http://p.f4ke.de/pzJkKO3I5H.png)

**Comment by carstene1ns** [comment]
Experimenting with Tabs:
![tabs](http://picload.org/image/wladgwd/hfg70j8fuj.png)

http://f4ke.de/dev/easyrpg/downloadpage/

**Comment by Ghabry** [comment]
:+1:
